program: /home/sam/Projects/SupervisedLearningCW/Tasks/sweeps/LC.py
entity: supervisedlearning
project: LC-sweeps
method: bayes
metric:
  goal: maximize
  name: "accuracy"
parameters:
  max_iter:
    max: 800
    min: 200
    distribution: int_uniform
  penalty:
    values: ['l2', 'none']
  tol:
    max: 1e-3
    min: 1e-4
  C:
    max: 1.2
    min: 0.8
  fit_intercept:
    values: [True, False]
  solver:
    values: ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
  l1_ratio:
    min: 0.0
    max: 1.0
