program: /home/sam/Projects/SupervisedLearningCW/Tasks/sweeps/MLP.py
method: bayes
metric:
  goal: minimize
  name: "loss"
parameters:
  hidden_layer_sizes:
    max: 300
    min: 75
    distribution: int_uniform
  max_iter:
    max: 600
    min: 150
    distribution: int_uniform
