program: /home/sam/Projects/SupervisedLearningCW/Tasks/sweeps/sweepRandomForest.py
entity: supervisedlearning
project: RF-sweeps
method: bayes
metric:
  goal: maximize
  name: "accuracy"
parameters:
  n_estimators:
    max: 500
    min: 50
    distribution: int_uniform
  criterion:
    values: ['gini', 'entropy']
  max_features:
    values: ['auto', 'sqrt', 'log2']
  min_samples_split:
    max: 5
    min: 1
  min_samples_leaf:
    max: 10
    min: 1
  min_weight_fraction_leaf:
    max: 0.5
    min: 0.0